add penelope tool
ShutdownRepo/Exegol-images pull request #410
Opened 2024-10-28 09:23 UTC by Frozenka

# Description

> This PR adds the installation function for Penelope, a shell handler designed to replace netcat when exploiting RCE vulnerabilities. 

# Related issues

> If your PR responds to an issue for a bug fix or feature request, make sure to includes references to the issues (e.g. "fixes #xxxx").

# Point of attention

> Things you are not sure about that deserve special attention if you have doubts or questions.

2024-10-28 12:41 UTC, QU35T-code commented
@Frozenka,

Can you synchronize (merge) with the remote dev branch ?
In addition, the `install_penelope` function is not called :

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/089a00ba-70aa-4833-91db-9cb4be43dc8d">

2024-10-28 12:46 UTC, QU35T-code requested changes

2024-10-28 12:46 UTC, QU35T-code commented on sources/install/package_network.sh
> +    deactivate
The project has a [pyproject.toml](https://github.com/brightio/penelope/blob/main/pyproject.toml), so you can use `pipx` to install it, which will be cleaner.

2024-10-28 12:46 UTC, QU35T-code commented on sources/install/package_network.sh
> +    add-test-command "penelope --help"
This command starts an interactive mode, which cannot be used for testing.

```bash
penelope --help
[+] Listening for reverse shells on 0.0.0.0:4444 →  127.0.0.1 • 198.19.249.2 • 192.168.0.1 • 192.168.228.1 • 172.22.0.1 • 172.19.0.1 • 192.168.207.1 • 172.20.0.1 • 192.168.215.1 • 192.168.186.1
➤  💀 Show Payloads (p) 🏠 Main Menu (m) 🔄 Clear (Ctrl-L) 🚫 Quit (q/Ctrl-C)
```

2024-10-28 12:46 UTC, QU35T-code commented on sources/install/package_network.sh
> +    add-aliases penelope
Can be removed after installation via pipx

2024-10-28 13:16 UTC, QU35T-code requested changes

2024-10-28 16:35 UTC, QU35T-code requested changes

2024-10-28 16:35 UTC, QU35T-code commented on sources/assets/shells/aliases.d/penelope
> +alias penelope="/opt/tools/penelope/venv/bin/python3 /opt/tools/penelope/penelope.py"
You can remove this unused file

2024-10-28 20:04 UTC, QU35T-code approved these changes

2024-10-29 09:26 UTC, QU35T-code commented
@Frozenka,

Penelope needs a display to show helper menu. I haven't found an command to test, so for the moment I can't approve.

2024-10-30 10:33 UTC, QU35T-code commented
https://github.com/brightio/penelope/blob/main/penelope.py#L4232

2024-11-08 16:56 UTC, ShutdownRepo commented
imo we can approve, if there's something wrong with penelope's tty we'll find a fix later on (or find a test command later on). It's not a huge priority.
The only thing I'm wondering is if we really need penelope, because pwncat-cs is already installed and it seems to me it's quite similar, am I wrong?

2024-11-08 19:07 UTC, QU35T-code commented
@Frozenka

2024-11-12 08:02 UTC, Frozenka commented
Hello, yes, actually, pwncat hasn't been maintained for several years. Penelope is a new, similar version that is currently maintained. :)

2024-11-14 16:04 UTC, cHJlaXpoZXI commented
> Hello, yes, actually, pwncat hasn't been maintained for several years. Penelope is a new, similar version that is currently maintained. :)

Indeed ! Penelope is maintained. Pwncat-cs, the last commit was made 2 years ago.and 48 issues without answers of maintainers.
 
> Penelope needs a display to show helper menu. I haven't found an command to test, so for the moment I can't approve.

The maintainer added a help option with argparse in the last version : 

```shell
 [Nov 14, 2024 - 16:52:57 (CET)] exegol-htb-gui penelope # python3 penelope.py -h
usage: penelope.py [-i] [-c] [-a] [-l] [-h] [-Q] [-d] [-L] [-T] [-CT] [-r]
                   [-m] [-H] [-P] [-S] [-C] [-U] [-s] [-p] [-pass] [-N] [-v]
                   [ports ...]

Penelope Shell Handler

positional arguments:
  ports                 Ports to listen/connect to, depending on -i/-c
                        options. Default: 4444

Reverse or Bind shell?:
  -i , --interface      Interface or IP address to listen on. Default: 0.0.0.0
  -c , --connect        Bind shell Host

Hints:
  -a, --hints           Show sample payloads for reverse shell based on the
                        registered Listeners
  -l, --interfaces      Show the available network interfaces
  -h, --help            show this help message and exit

Verbosity:
  -Q, --silent          Be a bit less verbose
  -d, --debug           Show debug messages

Session Logging:
  -L, --no-log          Do not create session log files
  -T, --no-timestamps   Do not include timestamps in session logs
  -CT, --no-colored-timestamps
                        Do not color timestamps in session logs

Misc:
  -r , --configfile     Configuration file location
  -m , --maintain       Maintain NUM total shells per target
  -H, --no-history      Disable shell history on target
  -P, --plain           Just land to the main menu
  -S, --single-session  Accommodate only the first created session
  -C, --no-attach       Disable auto attaching sessions upon creation
  -U, --no-upgrade      Do not upgrade shells

File server:
  -s, --serve           HTTP File Server mode
  -p , --port           File Server port. Default: 8000
  -pass , --password    URL prefix

Debug:
  -N , --no-bins        Simulate binary absence on target (comma separated
                        list)
  -v, --version         Show Penelope version
  ```
Regards,

2024-11-14 20:22 UTC, QU35T-code commented
> > Hello, yes, actually, pwncat hasn't been maintained for several years. Penelope is a new, similar version that is currently maintained. :)
> 
> Indeed ! Penelope is maintained. Pwncat-cs, the last commit was made 2 years ago.and 48 issues without answers of maintainers.
> 
> > Penelope needs a display to show helper menu. I haven't found an command to test, so for the moment I can't approve.
> 
> The maintainer added a help option with argparse in the last version :
> 
> ```shell
>  [Nov 14, 2024 - 16:52:57 (CET)] exegol-htb-gui penelope # python3 penelope.py -h
> usage: penelope.py [-i] [-c] [-a] [-l] [-h] [-Q] [-d] [-L] [-T] [-CT] [-r]
>                    [-m] [-H] [-P] [-S] [-C] [-U] [-s] [-p] [-pass] [-N] [-v]
>                    [ports ...]
> 
> Penelope Shell Handler
> 
> positional arguments:
>   ports                 Ports to listen/connect to, depending on -i/-c
>                         options. Default: 4444
> 
> Reverse or Bind shell?:
>   -i , --interface      Interface or IP address to listen on. Default: 0.0.0.0
>   -c , --connect        Bind shell Host
> 
> Hints:
>   -a, --hints           Show sample payloads for reverse shell based on the
>                         registered Listeners
>   -l, --interfaces      Show the available network interfaces
>   -h, --help            show this help message and exit
> 
> Verbosity:
>   -Q, --silent          Be a bit less verbose
>   -d, --debug           Show debug messages
> 
> Session Logging:
>   -L, --no-log          Do not create session log files
>   -T, --no-timestamps   Do not include timestamps in session logs
>   -CT, --no-colored-timestamps
>                         Do not color timestamps in session logs
> 
> Misc:
>   -r , --configfile     Configuration file location
>   -m , --maintain       Maintain NUM total shells per target
>   -H, --no-history      Disable shell history on target
>   -P, --plain           Just land to the main menu
>   -S, --single-session  Accommodate only the first created session
>   -C, --no-attach       Disable auto attaching sessions upon creation
>   -U, --no-upgrade      Do not upgrade shells
> 
> File server:
>   -s, --serve           HTTP File Server mode
>   -p , --port           File Server port. Default: 8000
>   -pass , --password    URL prefix
> 
> Debug:
>   -N , --no-bins        Simulate binary absence on target (comma separated
>                         list)
>   -v, --version         Show Penelope version
> ```
> 
> Regards,

Yes, but this line is called before the helper and needs a display…
https://github.com/ThePorgs/Exegol-images/pull/410#issuecomment-2446503723

2024-11-17 14:02 UTC, ShutdownRepo commented
Since pwncat-cs is not maintained anymore and penelope seems to a maintained alternative we might as well keep both and remove one in the future.
I wouldn't be against merging here even without the display test, but with a simple `-h` test instead, what do you think @QU35T-code

2025-02-18 15:57 UTC, ShutdownRepo commented
@Frozenka any news here on how to improve the unit testing?

2025-02-18 16:08 UTC, ShutdownRepo requested changes
let's change this and we should be almost good to go
let's have a better add-test-command as well if possible

2025-02-18 16:08 UTC, ShutdownRepo commented on sources/assets/shells/history.d/penelope
let's use long options here so that its self explainatory
I know it's not done everywhere at the moment but it should imo

2025-09-16 19:19 UTC, merged